name: sheeta
description: 'Social media application help you to share photos with your friends'
publish_to: 'none'
version: 0.1.4+5

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  # Firebase Services
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  firebase_storage: ^11.5.3
  cloud_firestore: ^4.13.3
  uuid: ^4.2.1
  # System
  provider: ^6.1.1
  intl: ^0.18.1
  path: ^1.8.3
  # Images Work
  flutter_svg: ^2.0.9
  image_picker: ^1.0.4
  photo_manager: ^3.0.0-dev.1
  permission_handler: ^11.1.0
  # Build
  flutter_launcher_icons: ^0.13.1
  # Files Work
  url_launcher: ^6.2.2
  # Designs
  fluttertoast: ^8.0.7
  image: ^4.1.3

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/sheeta.png'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
